### ISSUE TITLE
Define key questions

### ISSUE THREAD

**Issue by willu47** [OnSSET/onsset#27]
- If you were to write OnSSET from scratch, how would you go about it?
  - Would a workflow management system help? e.g. [snakemake](https://snakemake.readthedocs.io/en/stable/)
  - Could it be easily parallelised? e.g. using [Dask](dask.org)

- Who are your users? What information do they need?
  - How should a user interact with the package?

- What data is required?
- How should data be best stored?
- How best to support FAIR? - Findable, Accessible, Interoperable, Reproducible

- What are the performance requirements?

- Where is code duplicated?
- Where is code complicated?
- Where is code unreadable?
- Where is data hardcoded?

- Where does code often change (e.g. between projects)

**Comment by akorkovelos** [comment]
**Q: Who are your users?**

OnSSET code is used to produce high-level, spatially explicit screening analyses for electrification. That is, indicating and quantifying "optimal" split between competing electrification technologies under defined electrification goals and/or objectives. **Note!** that the code makes use of best available spatial and other information, which however are not (as of now) an integral part of the OnSSET code (this relates to another question on data).

So based on the definition above, I believe that the users can be classified in two groups:

A. **Modelers** that will work with code base, change and improve it.
B. **Electrification professionals** that are interested mainly in the output of an OnSSET-based analysis (rather than the code base per se).

Information and structure in this repo should focus on addressing the needs of **group A**.

-------------------------------------------------------------------------------------------------------
**Q: What information do they need? How should a user interact with the package?**

- General package info (objective, version, how-to-install, requirements, PyPI)
- Description of the workflow (sample input/output data, example, documentation)
- Open Source License 
- Contributing guidelines (example [here](https://github.com/atom/atom/blob/master/CONTRIBUTING.md))
- Code of conduct (see [here](https://www.contributor-covenant.org/))

**Comment by akorkovelos** [comment]
**Q What data is required?**

OnSSET code requires two types of input data:

1. **Geospatial data** providing information of the locality (e.g. resources, population distribution etc.)
2. **Socio-techno-economic data** providing information not bound to geography (e.g. cost of technologies, electrification objectives and goals)
